<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Panitia_model extends CI_Model
{

    public $table = 'tbl_panitia';
    public $id = 'id_panitia';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->load->model('Panitia_model');

    }

    //Relasikan Tabel
    function batch($limit, $start = 0, $q = Null)
    { 
        //Relasikan tabel dengan dinamis
        $this->db->join('tbl_batch', 'tbl_batch.id_batch = tbl_panitia.id_batch', $q);
        $this->db->limit($limit, $start)->order_by('id_panitia', 'DESC');
        return $this->db->get('tbl_panitia')->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->join('tbl_batch', 'tbl_batch.id_batch = tbl_panitia.id_batch');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_panitia', $q);
	$this->db->or_like('nama_panitia', $q);
	$this->db->or_like('id_batch', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_panitia', $q);
	$this->db->or_like('nama_panitia', $q);
	$this->db->or_like('id_batch', $q);
	$this->db->or_like('username', $q);
	$this->db->or_like('password', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Panitia_model.php */
/* Location: ./application/models/Panitia_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-03-31 16:08:59 */
/* http://harviacode.com */