<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Soal_model extends CI_Model
{

    public $table = 'tbl_soal';
    public $id = 'id_soal';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function matauji($limit, $start = 0, $q = NULL)
    {

        //Relasikan tabel dengan dinamis
        $this->db->join('tbl_matauji', 'tbl_matauji.id_matauji = tbl_soal.id_matauji', $q);
        $this->db->order_by('id_soal','DESC');
        $this->db->limit($limit, $start);
        return $this->db->get('tbl_soal')->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_soal', $q);
	$this->db->or_like('id_matauji', $q);
	$this->db->or_like('pertanyaan', $q);
	$this->db->or_like('pilihan_a', $q);
	$this->db->or_like('pilihan_b', $q);
	$this->db->or_like('pilihan_c', $q);
	$this->db->or_like('pilihan_d', $q);
    $this->db->or_like('pilihan_e', $q);
	$this->db->or_like('jawaban', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_soal', $q);
        $this->db->or_like('id_matauji', $q);
    	$this->db->or_like('pertanyaan', $q);
    	$this->db->or_like('pilihan_a', $q);
    	$this->db->or_like('pilihan_b', $q);
    	$this->db->or_like('pilihan_c', $q);
    	$this->db->or_like('pilihan_d', $q);
        $this->db->or_like('pilihan_e', $q);
    	$this->db->or_like('jawaban', $q);
    	$this->db->limit($limit, $start);
            return $this->db->get($this->table)->result();
        }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Soal_model.php */
/* Location: ./application/models/Soal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-02-20 12:22:30 */
/* http://harviacode.com */