<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ujian_model extends CI_Model
{

    public $table = 'tbl_ujian';
    public $id = 'id_ujian';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function peserta($limit, $start = 0, $q = NULL)
    {

        //Relasikan tabel dengan dinamis
        $this->db->join('tbl_peserta', 'tbl_peserta.id_peserta = tbl_ujian.id_peserta', $q);
        // $this->db->join('tbl_panitia', 'tbl_panitia.id_panitia = tbl_ujian.id_panitia', $q);
        // $this->db->join('tbl_batch', 'tbl_batch.id_batch = tbl_ujian.id_batch', $q);
        $this->db->order_by('id_ujian','DESC');
        $this->db->limit($limit, $start);
        return $this->db->get('tbl_ujian')->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_ujian', $q);
	$this->db->or_like('id_peserta', $q);
	$this->db->or_like('id_panitia', $q);
	$this->db->or_like('id_batch', $q);
	$this->db->or_like('jumlah_salah', $q);
	$this->db->or_like('jumlah_benar', $q);
	$this->db->or_like('nilai', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_ujian', $q);
	$this->db->or_like('id_peserta', $q);
	$this->db->or_like('id_panitia', $q);
	$this->db->or_like('id_batch', $q);
	$this->db->or_like('jumlah_salah', $q);
	$this->db->or_like('jumlah_benar', $q);
	$this->db->or_like('nilai', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ujian_model.php */
/* Location: ./application/models/Ujian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-29 05:32:59 */
/* http://harviacode.com */